# Generated by Django 5.1.4 on 2025-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('business_type', models.CharField(choices=[('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler'), ('Distributor', 'Distributor')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
            ],
        ),
    ]
